project:
  type: website

website:
  title: "OpenPipelines"
  image: "images/logo.svg"
  site-url: https://openpipelines.bio
  repo-url: https://github.com/openpipelines-bio/website
  navbar:
    logo: "images/logo_source.svg"
    title: false
    left:
      # - text: Architecture
      #   menu: 
      #     - architecture/index.qmd
      #     - architecture/status.qmd
      #     - architecture/use-cases.qmd
      #     - architecture/file-formats.qmd
      - components/index.qmd
      - guide/index.qmd
      - contributing/index.qmd

    right:
      - about/index.qmd
      - text: Source Code
        url: https://github.com/openpipelines-bio/openpipeline
  sidebar:
    - id: components
      collapse-level: 4
      title: Components
      contents: components
    - id: guide
      collapse-level: 3
      title: User Guide
      contents: guide
    - id: contributing
      collapse-level: 3
      title: Contributing
      contents:  contributing
  page-footer: "Copyright 2022, OpenPipelines.bio"
  repo-actions: [edit, issue] 
  google-analytics: G-KKE3LFPPV8

format:
  html:
    theme: [simplex, theme.scss]
    css: styles.css
    toc: true



