project:
  type: website

website:
  title: "OpenPipelines"
  image: "openpipelines.png"
  site-url: https://openpipelines.bio
  repo-url: https://github.com/openpipelines-bio/website
  navbar:
    logo: "images/logo_source.svg"
    title: false
    left:
      # - text: Architecture
      #   menu: 
      #     - architecture/index.qmd
      #     - architecture/status.qmd
      #     - architecture/use-cases.qmd
      #     - architecture/file-formats.qmd
      - sidebar:guide
      - sidebar:contributing
      - href: components/index.qmd
        text: Reference
      - sidebar:About

    right:
      - text: Source Code
        url: https://github.com/openpipelines-bio/openpipeline
  sidebar:
    - id: components
      collapse-level: 3
      title: Components
      contents: 
        - components/index.qmd
        - text: Workflows
          contents:
            - auto: "components/workflows/*/*"
        - text: Modules
          contents:
            - auto: "components/modules/*/*"
    - id: guide
      collapse-level: 3
      title: User Guide
      contents: 
        - auto: guide
    - id: contributing
      collapse-level: 3
      title: Contributing
      contents: 
        - contributing/getting_started.qmd
        - contributing/creating_components.qmd
        - contributing/creating_pipelines.qmd
        - contributing/project_structure.qmd
        - contributing/running_tests.qmd
        - contributing/pull_requests.qmd
    - id: About
      collapse-level: 2
      contents:
        - about/authors.qmd
        - about/openpipelines.qmd
  page-footer: "Copyright 2022, OpenPipelines.bio"
  repo-actions: [edit, issue] 
  google-analytics: G-KKE3LFPPV8

format:
  html:
    theme: [simplex, theme.scss]
    css: styles.css
    toc: true



