project:
  type: website

website:
  title: "OpenPipelines"
  navbar:
    background: primary
    left:
      - index.qmd
      - architecture.qmd
    right:
      - text: Source Code
        url: https://github.com/openpipelines-bio/openpipeline
  page-footer: "Copyright 2022, OpenPipelines-bio"
  repo-url: https://github.com/openpipelines-bio/openpipeline-web
  repo-actions: [edit, issue] 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



