project:
  type: website

website:
  title: "OpenPipelines"
  image: "openpipelines.png"
  site-url: https://openproblems.bio
  repo-url: https://github.com/openproblems-bio/website
  navbar:
    logo: "openpipelines.png"
    title: false
    left:
      - index.qmd
      - text: Architecture
        menu: 
          - architecture/index.qmd
          - architecture/use-cases.qmd
          - architecture/file-formats.qmd
      - href: components/index.qmd
        text: Components
      - text: Contribute
        href: contribute/index.qmd
    right:
      - text: Source Code
        url: https://github.com/openpipelines-bio/openpipeline
  sidebar:
    - id: components
      collapse-level: 3
      title: Components
      contents: 
        - components/index.qmd
        - text: Workflows
          contents:
            - auto: "components/workflows/*/*"
        - text: Modules
          contents:
            - auto: "components/modules/*/*"
  page-footer: "Copyright 2022, OpenPipelines.bio"
  repo-actions: [edit, issue] 
  google-analytics: G-KKE3LFPPV8

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



